version: 0.2

phases:
  install:
    commands:
      # Install dependencies needed for running tests
      - npm install

       # Install pip
      - sudo apt-get install python-pip

      # Upgrade AWS CLI to the latest version
      - pip install --upgrade awscli
