branch-defaults:
  master:
    environment: bogdaproste-backend-dev
    group_suffix: null
global:
  application_name: bogdaproste-backend
  branch: null
  default_ec2_keyname: aws-eb
  default_platform: Node.js
  default_region: eu-central-1
  include_git_submodules: true
  instance_profile: null
  platform_name: null
  platform_version: null
  profile: eb-deploy-user
  repository: null
  sc: git
  workspace_type: Application
